### ISSUE TITLE
[packages/core:jsx-runtime] create v2.x new jsx runtime

### ISSUE THREAD

**Issue by Theryston** [Theryston/jsx-mail#128]
The runtime has a "simple" thing to do: return a virtual DOM from the jsx

All the files are built with the [core prepare](#127 ) and when it is built we define to use the `@jsx-mail/core/jsx-runtime` as the jsx runtime.

**Todo**

- [x] Create a tag virtual DOM for each tag, and create a file for each tag process. That file will be able to process the tag and return a virtual DOM
- [x] Think about the styles, how can we to do that?
- [x] Create the jsx.d.ts types for all created tags
